spring:
  profiles:
    active:
      - dev
      
---
spring:
  profiles: dev  #开发环境
  application:
    name: microserviceCloud-config-xh-dev
    
    
    
---
spring:
  profiles: test  #测试环境
  application:
    name: microserviceCloud-config-xh-test
    
#请保存为UTF格式    
#test update    
   
                
